FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

RUN apt-get update
RUN apt-get install tesseract-ocr -y
RUN apt-get install libtesseract-dev -y
RUN apt-get install libsm6 libxrender1 libfontconfig1 libice6 -y
RUN apt install python3-opencv -y

WORKDIR /app

COPY requirements.txt /tmp/
RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt


COPY app/ /app/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]